feat: add jwt middleware and workspaceId middleware
BinaryStudioAcademy/bsa-2021-infostack pull request #10
Opened 2021-07-30 08:51 UTC by kopkop123

2021-07-30 09:17 UTC, aleksandr-kuharenko requested changes
You installed `cookie-parser` library but it is not used. 

> app.use(cookieParser())

Check example: https://www.npmjs.com/package/cookie-parser#example

2021-07-30 09:17 UTC, aleksandr-kuharenko commented on backend/package.json
> +    "@types/jsonwebtoken": "^8.5.4",
```suggestion
    "@types/jsonwebtoken": "8.5.4",
```

2021-07-30 09:17 UTC, aleksandr-kuharenko commented on backend/src/api/middlewares/authorization-middleware.ts
> +  }
workspaceId should be taken from req.cookies

2021-07-30 13:32 UTC, aleksandr-kuharenko commented on backend/src/api/middlewares/authorization-middleware.ts
> +  if(workspaceId === 'first') {
Remove test data, just throw an error if there is no workspaceId

2021-07-30 13:33 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +import { Request, Response } from 'express';
Remove this testing code

2021-07-30 14:55 UTC, neonila-kunyk requested changes

2021-07-30 14:55 UTC, neonila-kunyk commented on backend/src/api/middlewares/authorization-middleware.ts
> +export const permissions = (...permittedRoles: string[]) => {
B7. Function or method begins with a verb. (plural nouns are used to name arrays)

2021-07-30 14:55 UTC, neonila-kunyk commented on backend/src/config/jwt-config.ts
> +export const expiresHours = 2;
B8. Constant names are written in capital letters.

2021-07-30 14:55 UTC, neonila-kunyk commented on backend/src/api/middlewares/authorization-middleware.ts
> +export const checkWorkSpace = (req: Request, res: Response, next: NextFunction): void => {
Workspace is one word

2021-07-30 14:55 UTC, neonila-kunyk commented on backend/src/common/models/user/IRequestWithUser.ts
> +import { Request } from 'express';
B11. File/folder names are written in lowercase letters. Words are separated by hyphens.
IRequestWithUser.ts supposed to be _request-with-user.interface.ts_

2021-07-30 14:55 UTC, neonila-kunyk commented on backend/src/services/user.service.ts
>  export const getSomething = <T>(data: T): Promise<T> => Promise.resolve(data);
B18. There are no files, modules and parts of code that aren't used in the project code, including commented code pats.

2021-07-30 16:33 UTC, kopkop123 commented on backend/src/services/user.service.ts
>  export const getSomething = <T>(data: T): Promise<T> => Promise.resolve(data);
getSomething is used in other files

2021-07-30 16:56 UTC, neonila-kunyk approved these changes, later dismissed

2021-08-02 07:48 UTC, aleksandr-kuharenko commented on backend/src/api/middlewares/authorization-middleware.ts
> +  } else {
add workspaceId to req

2021-08-02 07:49 UTC, aleksandr-kuharenko commented on backend/src/api/middlewares/authorization-middleware.ts
> +    const { userId, role } = req;
You do not have `role` in req here, because in `auth` middleware you add only 'userId'

2021-08-02 07:56 UTC, aleksandr-kuharenko commented on backend/src/services/user.service.ts
> +};
when development is finished, remove this code. (with `router
  .post('/', jwtLogin);`)

B18. There are no files, modules and parts of code that aren't used in the project code, including commented code parts.

2021-08-02 08:13 UTC, AlikRakhmonov requested changes

2021-08-02 08:13 UTC, AlikRakhmonov commented on backend/src/api/routes/index.ts
> +  app.use(cookieParser());
it should be in server.ts

2021-08-02 08:13 UTC, AlikRakhmonov commented on backend/src/common/models/user/request-with-user.interface.ts
> +  role?: string;
role is enum

2021-08-02 08:13 UTC, AlikRakhmonov commented on backend/src/api/middlewares/authorization-middleware.ts
> +};
every middleware should be in a separate file

2021-08-02 08:13 UTC, AlikRakhmonov commented on backend/src/api/middlewares/authorization-middleware.ts
> +export const permit = (...permittedRoles: string[]) => {
array of enums

2021-08-02 12:06 UTC, AlikRakhmonov requested changes

2021-08-02 12:06 UTC, AlikRakhmonov commented on backend/src/api/routes/index.ts
> +  app.use('/api/users', auth, checkWorkspace, userRoute);
middlewares should be in server.ts

2021-08-02 12:06 UTC, AlikRakhmonov commented on backend/src/api/routes/index.ts
> +  app.use('/api/login', authRoute);
rollback

2021-08-02 12:06 UTC, AlikRakhmonov commented on backend/src/services/user.service.ts
> +export const jwtLogin = async (req: IRequestWithUser, res: Response): Promise<void> => {
delete this method
merge dev branch, there is Sign In / Sign Up flow already, make it work together

2021-08-02 12:06 UTC, AlikRakhmonov commented on backend/src/api/middlewares/check-workspace-middleware.ts
> +    req.workspaceId = workspaceId;
move it to auth middleware

2021-08-02 12:08 UTC, AlikRakhmonov requested changes

2021-08-02 12:08 UTC, AlikRakhmonov commented on backend/src/common/models/workspace/request-with-workspace.interface.ts
> +  workspaceId?: string;
move it to IRequestWithUser

2021-08-02 12:10 UTC, AlikRakhmonov requested changes

2021-08-02 12:10 UTC, AlikRakhmonov commented on backend/src/api/middlewares/authorization-middleware.ts
> +    res.status(HttpCode.INTERNAL_SERVER_ERROR).json({ msg: 'Something wrong', error: err });
401 unauthorized

2021-08-02 12:23 UTC, AlikRakhmonov requested changes

2021-08-02 12:23 UTC, AlikRakhmonov commented on backend/src/api/middlewares/authorization-middleware.ts
> +    res.status(HttpCode.INTERNAL_SERVER_ERROR).json({ msg: 'Something wrong', error: err });
```suggestion
    res.status(HttpCode.UNAUTHORIZED).json({ msg: 'Unauthorized', error: err });
```

2021-08-02 12:42 UTC, AlikRakhmonov requested changes

2021-08-02 12:42 UTC, AlikRakhmonov commented on backend/src/api/middlewares/authorization-middleware.ts
> +  try {
check req.path if it's in white list

2021-08-02 12:42 UTC, AlikRakhmonov commented on backend/src/api/middlewares/permissions-middleware.ts
> +    const { userId, role } = req;
role is not in req. Get role from DB by userId and workspaceId

2021-08-02 16:26 UTC, AlikRakhmonov approved these changes

2021-08-02 16:27 UTC, merged