fix: workspace name validation
BinaryStudioAcademy/bsa-2021-infostack pull request #124
Opened 2021-08-12 19:51 UTC by DeniGolf

2021-08-12 21:14 UTC, aleksandr-kuharenko requested changes

2021-08-12 21:14 UTC, aleksandr-kuharenko commented on frontend/src/validations/account-info-schema.ts
>        'Full name must consist of latin letters (upper and lower case), numbers, and symbols',
why title everywhere?

2021-08-12 21:14 UTC, aleksandr-kuharenko commented on frontend/src/validations/login-schema.ts
> +      titleRegex,
the same question

2021-08-13 05:46 UTC, DeniGolf commented on frontend/src/validations/account-info-schema.ts
>        'Full name must consist of latin letters (upper and lower case), numbers, and symbols',
> why title everywhere?

because it's the same RegEx. Also it can be used not only for fullName

2021-08-13 06:11 UTC, DeniGolf commented on frontend/src/validations/account-info-schema.ts
>        'Full name must consist of latin letters (upper and lower case), numbers, and symbols',
> > why title everywhere?
> 
> because it's the same RegEx. Also it can be used not only for fullName

I returned passwordRegex

2021-08-13 10:32 UTC, ursarik approved these changes

2021-08-13 10:49 UTC, aleksandr-kuharenko approved these changes

2021-08-13 11:06 UTC, SirRedrick approved these changes

2021-08-13 13:47 UTC, merged