Fix/tags settings
BinaryStudioAcademy/bsa-2021-infostack pull request #146
Opened 2021-08-15 16:14 UTC by zalevskyi

[task description](https://trello.com/c/KvBARoVc/21-add-an-ability-to-manage-tags-in-settings)

2021-08-15 20:45 UTC, neonila-kunyk approved these changes

2021-08-15 20:45 UTC, neonila-kunyk commented on backend/src/services/tag.service.ts
> +import { ITag } from 'infostack-shared/common/interfaces';
No imports from infostack-shared

2021-08-15 21:17 UTC, SirRedrick requested changes

2021-08-15 21:17 UTC, SirRedrick commented on frontend/src/store/tags/actions.ts
> +    } catch (err) {
Why do you handle an empty tag name in asyncThunk and not inside the component?

2021-08-15 21:23 UTC, SirRedrick requested changes

2021-08-15 21:23 UTC, SirRedrick commented on frontend/src/store/tags/slice.ts
> +  tagEditError: string | null;
What is the purpose of having these values in the state?

2021-08-15 21:23 UTC, SirRedrick commented on frontend/src/store/tags/slice.ts
> +      state.tagAddName = null;
Please read redux docs on how to use asyncThunks with extra reducers:
https://redux.js.org/tutorials/essentials/part-5-async-logic#reducers-and-loading-actions

2021-08-16 11:15 UTC, zalevskyi commented on frontend/src/store/tags/slice.ts
> +      state.tagAddName = null;
Sorry, but I don't understang your proposal
asyncThunks actions are used for network requests and by adding extra reducers you can manage their promise state
But this action RESET_TAGS is used with useEffect() in the tags-settings component
```
useEffect(() => {
    dispatch(tagActions.loadTags());
    return (): void => {
      dispatch(tagActions.resetTags());
    };
  }, []);
```
It clears state when user leaves tag settings page.
It is purpose to update tags list each time user is coming back to tags settings page visually showing spinner each time.
With out it user can revisit page and see right away the old list of tags and only then the component will reload them without clear indicating to user by means of spinner updating in the list.
It has nothing about async actions. It is about clearing on component unmount
That is about basic React task of [clearing effect](https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect)

2021-08-16 12:09 UTC, zalevskyi commented on frontend/src/store/tags/actions.ts
> +    } catch (err) {
First of all we have to handle errors that comes from server and show them to user.
BE is the king in the apps bussiness logic.
Errors that server can send at the moment are: 1) Empy tag name 2) Duplicate tag
The component could not know server response by itself, only via store (via asyncThunks).
That is why the store must know about all errors that come from the server and manage the component state accordingly.
That is why you can not avoid managing errors via store. (Or just I don't know how)
Yes, some errors FE can anticipate on its own (like empy tag name), while some of them only server can judge (like duplicate tag).
You can for sure decrease server workload by preventing request that FE can know to be inproper.
But at this point you already have a way to manage in FE all errors from BE (as it is a must have).
And you have to options:
1) just adjust already available way to manage errors from server, by just tweaking it
2) add another checking system on top of the one you have already.
I choose the first way as more simple, streamline and easier to understand.
In the second option a person who maintain the project will have to get understanding of both system instead of one. And just by statistics: double the way system is working - double probability of hard to catch bugs.
I am not asserting that my solution is the best. I like simplier solutions and just didn't find better.
Could you please give a link on example of more better solution to managing errors from the server and for some of them preventing unnecessary requests on FE side. Or just fork this branch and commit your proposal on this part?

2021-08-16 12:11 UTC, zalevskyi commented on frontend/src/store/tags/slice.ts
> +  tagEditError: string | null;
To manage errors that come from the server.
I would appreciate suggestion how to manage them with out asynkThunks and store

2021-08-16 12:11 UTC, SirRedrick approved these changes

2021-08-16 12:25 UTC, merged

2021-08-16 12:36 UTC, AlikRakhmonov commented on frontend/src/store/tags/actions.ts
> +    } catch (err) {
@zalevskyi Your component is responsible for handling an empty field. Store Action does not care about what is passed to it. It just passes data to the server and the server responses with data or an error. Then Store Action put the data or the error to the Store or just passes it back to the component. It's called layer of responsibility.