Feat/delete users from user settings
BinaryStudioAcademy/bsa-2021-infostack pull request #151
Opened 2021-08-16 16:05 UTC by AndriiPopov3

2021-08-16 21:53 UTC, ursarik reviewed
why not create just one endpoint on the backend, where you will delete user from workspace, remove all permissions and unfollow pages? for example
    `api/workspaces/:id/users/:userId`

2021-08-16 23:21 UTC, neonila-kunyk approved these changes

2021-08-16 23:21 UTC, neonila-kunyk commented on frontend/src/components/common/delete-modal/delete-modal.tsx
> +export const DeleteModal: React.FC<Props> = ({
If you make common delete modal component, maybe it will be better to take out the confirmation function, leaving the universal component
And maybe it can be just confirm modal that receives title and body

2021-08-16 23:21 UTC, neonila-kunyk commented on frontend/src/components/common/delete-modal/delete-modal.tsx
> +  const handleClose = (): void => {
Unnecesary function, use onModalClose directly

2021-08-17 09:45 UTC, AlikRakhmonov requested changes

2021-08-17 09:45 UTC, AlikRakhmonov commented on backend/src/api/routes/workspace-route.ts
> +  .put(
```suggestion
  .delete(
```

2021-08-17 09:45 UTC, AlikRakhmonov commented on backend/src/api/routes/workspace-route.ts
> +    '/:id/delete-user',
```suggestion
    '/:workspaceId/user/:userId',
```

2021-08-17 09:45 UTC, AlikRakhmonov commented on backend/src/api/routes/workspace-route.ts
> +    '/:id/delete-user',
check if you have an access to the workspace where you delete the user
check please that you are Admin because User can't delete users

2021-08-17 09:47 UTC, AlikRakhmonov requested changes

2021-08-17 09:47 UTC, AlikRakhmonov commented on backend/src/services/workspace.service.ts
> +    if (userWorkspace.status !== InviteStatus.DELETED) {
rollback changes, user should be able to see deleted users

2021-08-17 09:51 UTC, AndriiPopov3 commented on backend/src/services/workspace.service.ts
> +    if (userWorkspace.status !== InviteStatus.DELETED) {
Admin is able to see deleted users in settings, this part of code is added so that if a user was deleted from the workspace they will not be able to see it on selection screen

2021-08-17 09:55 UTC, AndriiPopov3 commented on backend/src/api/routes/workspace-route.ts
> +    '/:id/delete-user',
Can't we just use permit middleware for this before calling delete function instead of changing route?

2021-08-17 14:12 UTC, AlikRakhmonov commented on backend/src/api/routes/workspace-route.ts
> +    '/:id/delete-user',
yes, you can use `permit`

2021-08-17 14:22 UTC, AlikRakhmonov approved these changes

2021-08-17 14:25 UTC, merged