New/view workspace users
BinaryStudioAcademy/bsa-2021-infostack pull request #16
Opened 2021-08-02 14:43 UTC by ursarik

2021-08-02 15:23 UTC, AlexKapic commented on frontend/src/components/workspace/users-settings/user-item/teams/teams.tsx
> +import { IWorkspaceUser } from '../../../../../common/interfaces/workspace/index';
maybe import from 'infostack-shared/common/interfaces'

2021-08-02 15:35 UTC, AlexKapic commented on frontend/src/services/workspace-api/workspace-api.service.ts
> +      method: HttpMethod.GET,
in http.service GET it's default method

2021-08-02 15:41 UTC, aleksandr-kuharenko requested changes

2021-08-02 15:41 UTC, aleksandr-kuharenko commented on frontend/src/services/workspace-api/workspace-api.service.ts
> +    const response: IWorkspaceUser[] = await http.load(this.BASE + 'users', {
```suggestion
  private BASE = '/api/workspaces';

  public async loadUsers(): Promise<IWorkspaceUser[]> {
    const response: IWorkspaceUser[] = await http.load(`${this.BASE}/users`, {
```

2021-08-02 15:41 UTC, aleksandr-kuharenko commented on backend/src/services/workspace.service.ts
> +export const getUsers = async (
```suggestion
export const getWorkspaceUsers = async (
```

2021-08-02 15:41 UTC, aleksandr-kuharenko commented on frontend/src/components/workspace/users-settings/user-item/add-role/add-role.tsx
> +const AddRole: React.FC = () => {
I think, "AddTeam" will be better
```suggestion
const AddTeam: React.FC = () => {
```

2021-08-02 15:44 UTC, aleksandr-kuharenko commented on frontend/src/components/workspace/users-settings/user-item/teams/teams.tsx
> +import { IWorkspaceUser } from '../../../../../common/interfaces/workspace/index';
```suggestion
import { IWorkspaceUser } from 'common/interfaces/workspace/index';
```

2021-08-02 15:53 UTC, ursarik commented on frontend/src/components/workspace/users-settings/user-item/add-role/add-role.tsx
> +const AddRole: React.FC = () => {
Dunno why i decided to name it AddRole :confused:

2021-08-02 16:40 UTC, aleksandr-kuharenko requested changes

2021-08-02 16:40 UTC, aleksandr-kuharenko commented on backend/src/api/routes/workspace-route.ts
> +);
PR with middlewares merged, you can update this

2021-08-02 16:40 UTC, aleksandr-kuharenko commented on backend/src/common/mappers/workspace/map-workspace-to-workspace-users.ts
> +      teams: user.teams.map((team) => team.name),
```suggestion
    const { id, fullName, teams } = user;
    return {
      id,
      fullName,
      role,
      teams: teams.map(team => team.name),
```

2021-08-02 16:40 UTC, aleksandr-kuharenko commented on frontend/src/components/workspace/users-settings/user-item/user-item.tsx
> +import { getAllowedClasses } from '../../../../helpers/dom/dom';
```suggestion
import { getAllowedClasses } from 'helpers/dom/dom';
```

2021-08-02 16:40 UTC, aleksandr-kuharenko commented on frontend/src/components/workspace/users-settings/user-item/user-item.tsx
> +import { IWorkspaceUser } from '../../../../common/interfaces/workspace';
Update all nested imports 
```suggestion
import { IWorkspaceUser } from 'common/interfaces/workspace';
```

2021-08-03 08:06 UTC, aleksandr-kuharenko approved these changes

2021-08-03 09:49 UTC, AlexKapic approved these changes

2021-08-03 09:53 UTC, merged