New/toolbar
BinaryStudioAcademy/bsa-2021-infostack pull request #31
Opened 2021-08-04 15:55 UTC by ovchynnikov

2021-08-04 16:04 UTC, aleksandr-kuharenko requested changes

2021-08-04 16:04 UTC, aleksandr-kuharenko commented on backend/src/data/repositories/page-repository.ts
> -
This blank line needed here =)

2021-08-04 16:04 UTC, aleksandr-kuharenko commented on backend/src/services/page.service.ts
> +export const getPages = async (req: IRequestWithUser): Promise<Page[]> => {
do not send `req` to service. Only needed payload

2021-08-04 16:04 UTC, aleksandr-kuharenko commented on backend/src/services/page.service.ts
> +  }
why interface is defined in body of service?

2021-08-04 16:07 UTC, aleksandr-kuharenko commented on backend/src/data/repositories/page-repository.ts
> +      where: { workspaceId: workspaceId },
```suggestion
      where: { workspaceId },
```

2021-08-04 16:09 UTC, aleksandr-kuharenko commented on frontend/src/components/toolbar/components/plus-button/plus-button.tsx
> +export default PlusButton;
we use https://icons.getbootstrap.com/ for icons, check example in our codebase

2021-08-04 16:10 UTC, aleksandr-kuharenko commented on shared/package.json
> +    "dependencies": {}
revert these changes back

2021-08-04 16:11 UTC, aleksandr-kuharenko commented on frontend/src/components/toolbar/toolbar.tsx
> +          </Accordion>
remove all hard code

2021-08-05 09:35 UTC, ovchynnikov commented on shared/package.json
> +    "dependencies": {}
can't make a revert, just copied the correct spacing from package.json file on develop branch. My file was changed by vscode

2021-08-05 11:25 UTC, AndriiPopov3 approved these changes

2021-08-05 11:38 UTC, AlikRakhmonov approved these changes

2021-08-05 11:45 UTC, aleksandr-kuharenko approved these changes

2021-08-05 11:48 UTC, merged

2021-08-05 11:54 UTC, ursarik approved these changes