Feat/export pdf
BinaryStudioAcademy/bsa-2021-infostack pull request #312
Opened 2021-09-01 17:21 UTC by kopkop123

2021-09-01 20:06 UTC, SirRedrick requested changes, later dismissed

2021-09-01 20:06 UTC, SirRedrick commented on backend/src/api/routes/page-route.ts
> +);
Shouldn't that be get?

2021-09-01 21:03 UTC, AlikRakhmonov requested changes

2021-09-01 21:03 UTC, AlikRakhmonov commented on backend/src/common/utils/generate-pdf.util.ts
> +      ? puppeteer.connect({ browserWSEndpoint: 'wss://chrome.browserless.io/' })
Must be only connect option

2021-09-02 04:55 UTC, kopkop123 commented on backend/src/api/routes/page-route.ts
> +);
fixed

2021-09-02 04:55 UTC, kopkop123 commented on backend/src/common/utils/generate-pdf.util.ts
> +      ? puppeteer.connect({ browserWSEndpoint: 'wss://chrome.browserless.io/' })
fixed

2021-09-02 07:15 UTC, AlikRakhmonov commented
I do not see `.env.example` changes. You should have at least `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`

https://github.com/puppeteer/puppeteer/blob/v10.2.0/docs/api.md#environment-variables

2021-09-02 07:15 UTC, AlikRakhmonov requested changes, later dismissed
see my comment

2021-09-02 08:19 UTC, AlikRakhmonov approved these changes

2021-09-02 08:51 UTC, SirRedrick approved these changes

2021-09-02 09:31 UTC, merged