Fix/add toast when change the role of the user in workspace
BinaryStudioAcademy/bsa-2021-infostack pull request #331
Opened 2021-09-03 13:01 UTC by AlexKapic

2021-09-04 15:04 UTC, neonila-kunyk approved these changes

2021-09-04 17:59 UTC, DeniGolf approved these changes

2021-09-04 21:10 UTC, SirRedrick requested changes

2021-09-04 21:10 UTC, SirRedrick commented on frontend/src/components/settings/components/users-settings/users-settings.tsx
> +    });
Promise from dispatch is always resolved, therefore `.then` handler will execute even if server rejected the action. To get the underlying promise that either resolves to **fulfilled** or **rejected** you need to call `.unwrap()` on `dispatch`.

Right now this toast with success message is displayed even if we could not change the user's role because of some error.

```suggestion
    dispatch(usersActions.chageRole({ userId, role }))
      .unwrap()
      .then(() => toast.info(`${fullname} role in the workplace has changed to ${role}`))
      .catch(() => toast.error('An error happened while changing role of the user'));
```

2021-09-05 14:18 UTC, SirRedrick approved these changes

2021-09-05 14:25 UTC, merged