feat: add header
BinaryStudioAcademy/bsa-2021-infostack pull request #6
Opened 2021-07-29 09:28 UTC by zalevskyi

Please review header
[Task details](https://trello.com/c/xAnbODhb/15-implement-header)
Overall it seems that task lacks sidebar toggle button

2021-07-29 10:18 UTC, aleksandr-kuharenko requested changes

2021-07-29 10:18 UTC, aleksandr-kuharenko commented on frontend/src/components/header/components/nav-profile.tsx
> +        <Dropdown.Item href="#/workspace">Select Workspace</Dropdown.Item>
Use "Link" component and Enum for routes. For all other links as well.
```suggestion
        <Dropdown.Item><Link to={AppRoute.WORKSPACES}>Select Workspace</Link></Dropdown.Item>
```

2021-07-29 10:18 UTC, aleksandr-kuharenko commented on frontend/src/components/header/header.tsx
> +import './header.css';
We use Scss for styles, please change the extension

2021-07-29 10:18 UTC, aleksandr-kuharenko commented on frontend/src/assets/img/notification-none.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#6c757d" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-
Lets use bootstrap [icons](https://icons.getbootstrap.com/#styling). 
For example: `<i class="bi bi-person"></i>`

Here is the list of icons for the header:
notification - https://icons.getbootstrap.com/icons/bell-slash/
profile icon - https://icons.getbootstrap.com/icons/person/
search icon - https://icons.getbootstrap.com/icons/search/
avatar mock - https://icons.getbootstrap.com/icons/person-circle/

2021-07-29 10:20 UTC, aleksandr-kuharenko commented
> Overall it seems that task lacks sidebar toggle button

Let's skip it for now. We will add this in the next iterations.

2021-07-30 13:35 UTC, aleksandr-kuharenko approved these changes

2021-07-30 18:47 UTC, ursarik approved these changes

2021-07-31 10:02 UTC, merged