feat: workspace name is displayed in toolbar
BinaryStudioAcademy/bsa-2021-infostack pull request #62
Opened 2021-08-06 19:00 UTC by SirRedrick

2021-08-06 19:28 UTC, ursarik approved these changes

2021-08-06 19:45 UTC, aleksandr-kuharenko approved these changes

2021-08-06 19:45 UTC, aleksandr-kuharenko commented on backend/src/api/routes/workspace-route.ts
> +  .get('/workspace/:id', run((req) => getOne(req.params.id, req.userId)));
You already have "/api/workspaces" [here](https://github.com/BinaryStudioAcademy/bsa-2021-infostack/blob/e01259c5aee6a9dbbc79e9bd7cf852360bae4b93/backend/src/api/routes/index.ts#L11)

2021-08-06 19:45 UTC, aleksandr-kuharenko requested changes
Fix endpoint

2021-08-06 20:15 UTC, SirRedrick commented on backend/src/api/routes/workspace-route.ts
> +  .get('/workspace/:id', run((req) => getOne(req.params.id, req.userId)));
"api/workspaces/:id" is already in use, should I repurpose it?

2021-08-06 20:20 UTC, aleksandr-kuharenko commented on backend/src/api/routes/workspace-route.ts
> +  .get('/workspace/:id', run((req) => getOne(req.params.id, req.userId)));
As I understood, `api/workspaces/:id` currently is used to get all workspaces for the user. And the Id in endpoint is userId. It should not be like this...
Move this functionality to `api/users/:id/workspaces` endpoint. 
And use `api/workspaces/:id` to get workspace by id

2021-08-08 18:13 UTC, ursarik commented on backend/src/api/routes/workspace-route.ts
> +  .get('/', run(req => getUserWorkspaces(req.userId)))
why do we need this if we have a route `/api/users/:id/workspaces` which does the same

2021-08-09 07:41 UTC, ursarik approved these changes

2021-08-09 08:12 UTC, aleksandr-kuharenko approved these changes

2021-08-09 09:00 UTC, merged