fix: change s3 storing logic
BinaryStudioAcademy/bsa-2021-infostack pull request #64
Opened 2021-08-06 23:37 UTC by DeniGolf

2021-08-07 13:49 UTC, neonila-kunyk approved these changes

2021-08-08 21:30 UTC, ursarik requested changes

2021-08-08 21:30 UTC, ursarik commented on backend/src/common/helpers/s3-file-storage.helper.ts
> +  }
```suggestion
  const params = { Bucket: bucketName, Key: fileName };
  return s3.headObject(params).promise();
```

2021-08-08 21:30 UTC, ursarik commented on backend/src/common/helpers/s3-file-storage.helper.ts
> +  }
```suggestion
  const params = { Bucket: bucketName, Key: fileName };
  return s3.deleteObject(params).promise();
```

2021-08-08 21:30 UTC, ursarik commented on backend/src/services/user.service.ts
> +    deleteFile(userToUpdate.avatar);
as i know if it will throw error then UnhandledPromiseRejectionWarning will appear which in future may terminate Node.js process

```suggestion
    await deleteFile(userToUpdate.avatar);
```

2021-08-10 08:29 UTC, aleksandr-kuharenko approved these changes

2021-08-10 08:32 UTC, ursarik approved these changes

2021-08-10 08:32 UTC, merged