feat: add tags settings
BinaryStudioAcademy/bsa-2021-infostack pull request #78
Opened 2021-08-09 06:00 UTC by zalevskyi

[Task description](https://trello.com/c/KvBARoVc/21-add-an-ability-to-manage-tags-in-settings)

2021-08-09 08:30 UTC, AlikRakhmonov requested changes

2021-08-09 08:30 UTC, AlikRakhmonov commented on backend/src/data/entities/tag.ts
> +  workspaceId: string;
rollback, it was correct

2021-08-09 08:30 UTC, AlikRakhmonov commented on backend/src/data/entities/tag.ts
> +  @ManyToOne(() => Workspace, (workspace) => workspace.tags)
rollback

2021-08-09 08:30 UTC, AlikRakhmonov commented on backend/src/data/entities/tag.ts
> +  @ManyToMany(() => Page, (page) => page.tags)
rollback

2021-08-09 08:30 UTC, AlikRakhmonov commented on backend/src/services/tag.service.ts
> +  if (newTag.name.length === 0) {
```suggestion
  if (!newTag.name) {
```

2021-08-09 08:31 UTC, aleksandr-kuharenko commented on frontend/src/store/tags/slice.ts
> +      // state.tagToEdit = null;
remove unused code

2021-08-09 09:35 UTC, aleksandr-kuharenko approved these changes

2021-08-09 12:22 UTC, ursarik commented on backend/src/data/repositories/tag.repository.ts
> +  }
```suggestion
  public findById(id: string): Promise<Tag> {
    return this.findOne({ id });
  }
  
  public findAllByWorkspaceId(workspaceId: string): Promise<Tag[]> {
    return this.find({ workspaceId });
  }
```

2021-08-09 12:22 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  return tags.map(({ id, workspaceId, name }) => ({ id, workspaceId, name }));
shouldn't it be in separate file? in `backend/src/common/mappers`

2021-08-09 12:22 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  if (tagsInDB.length > 0) {
```suggestion
  if (tagsInDB.length) {
```

2021-08-09 12:22 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  if (result.affected === 0) {
```suggestion
  if (!result.affected) {
```

2021-08-09 12:22 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  return;
```suggestion
```

2021-08-09 12:22 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  if (result.affected === 0) {
```suggestion
  if (!result.affected) {
```

2021-08-09 15:27 UTC, zalevskyi commented on backend/src/services/tag.service.ts
> +  return tags.map(({ id, workspaceId, name }) => ({ id, workspaceId, name }));
Not exactly.
I prefer to use built in RDBMS query tools, rather then inventing mapping wheels
Redone repository

2021-08-09 15:52 UTC, ursarik commented on backend/src/services/tag.service.ts
> +  return await tagRepository.findAllByWorkspaceId(workspaceId);
```suggestion
  return tagRepository.findAllByWorkspaceId(workspaceId);
```

2021-08-10 07:06 UTC, AlikRakhmonov approved these changes

2021-08-10 08:42 UTC, DeniGolf approved these changes

2021-08-10 10:24 UTC, merged