feat: add teams settings
BinaryStudioAcademy/bsa-2021-infostack pull request #79
Opened 2021-08-09 06:28 UTC by schernaya

2021-08-09 08:11 UTC, aleksandr-kuharenko commented on frontend/src/components/workspace/team-settings/item/item.tsx
> +import { ITeamUser } from 'infostack-shared/common/interfaces/team/team-user.interface';
use import from frontend/common 
https://github.com/BinaryStudioAcademy/bsa-2021-infostack/pull/79/files#diff-82c3f88b88e63c5e08a22128ff259d8ab27c5c2a05f8cd70b99b760bfb2a9302R1

2021-08-09 08:26 UTC, AlikRakhmonov requested changes

2021-08-09 08:26 UTC, AlikRakhmonov commented on backend/src/api/routes/index.ts
> +  app.use('/api/settings', settingsRoute);
`/api/teams`

rename routes, services on the backend

2021-08-09 18:06 UTC, ghost approved these changes

2021-08-10 06:48 UTC, aleksandr-kuharenko approved these changes

2021-08-10 07:05 UTC, AlikRakhmonov approved these changes

2021-08-10 07:37 UTC, merged