feat: not found page
BinaryStudioAcademy/bsa-2021-infostack pull request #81
Opened 2021-08-09 11:54 UTC by DeniGolf

2021-08-09 12:53 UTC, aleksandr-kuharenko approved these changes

2021-08-09 20:06 UTC, SirRedrick requested changes

2021-08-09 20:06 UTC, mykytabatrak commented on frontend/src/components/main/main.tsx
> +      <Route path="*" component={NotFound} />
The sole purpose of the `Main` component was to render things with `Toolbar` and `Header`, why is 404 page inside `Main` and not inside `App`?

2021-08-09 20:06 UTC, SirRedrick commented on frontend/src/components/not-found/not-found.tsx
> +      )} d-flex flex-column`}
You don't need to wrap this in a template literal, `getAllowedClasses` accepts both strings and objects
```suggestion
className={getAllowedClasses(styles.notFoundWrapper), 'd-flex flex-column'}
```

2021-08-09 20:06 UTC, SirRedrick commented on frontend/src/components/not-found/not-found.tsx
> +          <div className="d-table-cell align-middle">
Wouldn't flex-box be better to align something to the center
```suggestion
<Col sm={10} md={8} lg={6} className="d-flex flex-column justify-content-center vh-100">
```

2021-08-10 07:04 UTC, AlikRakhmonov commented
check if your build fails locally

2021-08-10 14:26 UTC, mykytabatrak approved these changes

2021-08-10 14:40 UTC, merged