Feat: show contributors & fix mulptiple page reload after F5
BinaryStudioAcademy/bsa-2021-infostack pull request #90
Opened 2021-08-10 16:42 UTC by ursarik

2021-08-10 20:11 UTC, SirRedrick commented on backend/src/data/seed-data/page-content.data.ts
> +  },
You don't need to provide id and createdAd properties, they are supplied by database as default values

2021-08-10 20:11 UTC, SirRedrick commented on backend/src/data/seed-data/user.data.ts
> +    id: 'bf873638-9388-4298-94b0-3d1a11ef8688',
Again, id is unnecessary

2021-08-10 21:42 UTC, aleksandr-kuharenko requested changes

2021-08-10 21:42 UTC, aleksandr-kuharenko commented on frontend/src/components/pages/components/page-contributors/page-contributors.tsx
> +import { AppRoute } from '../../../../common/enums/enums';
```suggestion
import { AppRoute } from 'common/enums/enums';
```

2021-08-10 21:42 UTC, aleksandr-kuharenko commented on frontend/src/components/pages/components/page-contributors/page-contributors.tsx
> +      AppRoute.PROFILE.slice(0, AppRoute.PROFILE.length - 3) + userId,
I think it is time to create a helper for this. Please, search in code all places with `.length - 3` and replace them with new helper everywhere

2021-08-10 21:43 UTC, aleksandr-kuharenko commented on backend/src/data/seed-data/page-content.data.ts
> +  },
Id is necessary for seeders. We should have the same data in DB after running the seeds.

2021-08-10 21:44 UTC, aleksandr-kuharenko commented
Please revert back IDs in seeders: https://github.com/BinaryStudioAcademy/bsa-2021-infostack/pull/90#discussion_r686342554

2021-08-11 06:59 UTC, SirRedrick approved these changes

2021-08-11 07:50 UTC, aleksandr-kuharenko approved these changes

2021-08-11 08:00 UTC, merged