New/following pages
BinaryStudioAcademy/bsa-2021-infostack pull request #91
Opened 2021-08-10 17:41 UTC by AndriiPopov3

2021-08-10 17:58 UTC, neonila-kunyk approved these changes

2021-08-10 22:03 UTC, aleksandr-kuharenko requested changes

2021-08-10 22:03 UTC, aleksandr-kuharenko commented on backend/src/services/page.service.ts
> +    }));
It is not the optimal approach. Please join PageContent to `followingPages` 
[example](https://github.com/typeorm/typeorm/issues/1270#issuecomment-348355428)

2021-08-10 22:03 UTC, aleksandr-kuharenko commented on backend/src/data/repositories/page.repository.ts
> +    return this.findOne({ relations: ['followingUsers'], where: { id: id } });
```suggestion
    return this.findOne({ relations: ['followingUsers'], where: { id } });
```

2021-08-10 22:03 UTC, aleksandr-kuharenko commented on frontend/src/components/pages/components/page-content/page-content.tsx
> +import { PageApi } from 'services';
We already call action to get page by id in this component. Why we cannot add information about page followers to existing request? We do not need extra requests

2021-08-10 22:03 UTC, aleksandr-kuharenko commented on frontend/src/components/profile-info/profile-info.tsx
> +import { UserApi, PageApi } from 'services';
The same here. If we already call UserAPI, can we add info about the followed pages to the response?

2021-08-11 14:15 UTC, aleksandr-kuharenko approved these changes

2021-08-11 14:38 UTC, ursarik approved these changes

2021-08-11 15:24 UTC, aleksandr-kuharenko requested changes

2021-08-11 15:24 UTC, aleksandr-kuharenko commented on frontend/src/store/pages/actions.ts
> +
you do not need async thunk here. You perform the synchronous operation.
Use action created in slice

2021-08-11 17:44 UTC, aleksandr-kuharenko approved these changes

2021-08-11 17:48 UTC, merged