New/page comments
BinaryStudioAcademy/bsa-2021-infostack pull request #93
Opened 2021-08-10 19:49 UTC by SirRedrick

2021-08-10 22:06 UTC, ursarik commented on backend/package.json
> +    "socket.io": "^4.1.3",
```suggestion
    "socket.io": "4.1.3",
```

2021-08-10 22:06 UTC, ursarik commented on backend/src/data/seed-data/comment.data.ts
> +    parentCommentId: null,
```suggestion
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, aut.',
    authorId: '9a25ad37-a647-4c1a-897f-59dbf275765d',
    pageId: 'f8cd8ff3-d1de-47a5-820e-73a58368b22e',
    parentCommentId: null,
```

id is added by db by default

2021-08-10 22:06 UTC, ursarik commented on backend/src/socket/handlers.ts
> +  socket.on('page/join', (pageId: string) => {
same about event names

2021-08-10 22:06 UTC, ursarik commented on backend/src/services/comment.service.ts
> +  io.to(pageId).emit('page/newComment', comment);
```suggestion
  io.to(pageId).emit(EVENT_NAMES.PAGE_NEW_COMMENT), comment);
```
what about moving event names to enum `EVENT_NAMES.ts` in `shared`? so in future we could import them in frontend and use instead of hardcoding them

2021-08-10 22:06 UTC, ursarik commented on backend/.env.example
> +SOCKET_PORT=3002
why ws should be on a separate port?

2021-08-10 22:06 UTC, ursarik commented on frontend/package.json
> +    "socket.io-client": "^4.1.3",
```suggestion
    "socket.io-client": "4.1.3",
```

2021-08-11 12:39 UTC, aleksandr-kuharenko commented on backend/.env.example
> +SOCKET_PORT=3002
I cannot see answer or changes, but conversation marked as resolved
@SirRedrick

2021-08-11 12:40 UTC, aleksandr-kuharenko requested changes
https://github.com/BinaryStudioAcademy/bsa-2021-infostack/pull/93#discussion_r686790626

2021-08-11 12:42 UTC, SirRedrick commented on backend/.env.example
> +SOCKET_PORT=3002
Sorry, I spoke to @AlikRakhmonov at the begging of out meeting, he said it will be okay both ways (on separate port and on the same), so I decided to do it how it was in the mini-project, on a separate port

2021-08-11 14:13 UTC, aleksandr-kuharenko approved these changes

2021-08-11 14:40 UTC, ursarik approved these changes

2021-08-11 14:52 UTC, merged